id = "pike"
name = "Pike"
version = "0.0.2"
schema_version = 1
authors = ["Oisín Mulhall <mulhalloisin@gmail.com>"]
description = "A modern Acme-inspired theme. No syntax highlighting."
repository = "https://github.com/eachra-bawn/pike"
